// Code generated by go-swagger; DO NOT EDIT.

package system_nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBetaSystemInformationParams creates a new GetBetaSystemInformationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBetaSystemInformationParams() *GetBetaSystemInformationParams {
	return &GetBetaSystemInformationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBetaSystemInformationParamsWithTimeout creates a new GetBetaSystemInformationParams object
// with the ability to set a timeout on a request.
func NewGetBetaSystemInformationParamsWithTimeout(timeout time.Duration) *GetBetaSystemInformationParams {
	return &GetBetaSystemInformationParams{
		timeout: timeout,
	}
}

// NewGetBetaSystemInformationParamsWithContext creates a new GetBetaSystemInformationParams object
// with the ability to set a context for a request.
func NewGetBetaSystemInformationParamsWithContext(ctx context.Context) *GetBetaSystemInformationParams {
	return &GetBetaSystemInformationParams{
		Context: ctx,
	}
}

// NewGetBetaSystemInformationParamsWithHTTPClient creates a new GetBetaSystemInformationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBetaSystemInformationParamsWithHTTPClient(client *http.Client) *GetBetaSystemInformationParams {
	return &GetBetaSystemInformationParams{
		HTTPClient: client,
	}
}

/*
GetBetaSystemInformationParams contains all the parameters to send to the API endpoint

	for the get beta system information operation.

	Typically these are written to a http.Request.
*/
type GetBetaSystemInformationParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get beta system information params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBetaSystemInformationParams) WithDefaults() *GetBetaSystemInformationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get beta system information params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBetaSystemInformationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get beta system information params
func (o *GetBetaSystemInformationParams) WithTimeout(timeout time.Duration) *GetBetaSystemInformationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get beta system information params
func (o *GetBetaSystemInformationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get beta system information params
func (o *GetBetaSystemInformationParams) WithContext(ctx context.Context) *GetBetaSystemInformationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get beta system information params
func (o *GetBetaSystemInformationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get beta system information params
func (o *GetBetaSystemInformationParams) WithHTTPClient(client *http.Client) *GetBetaSystemInformationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get beta system information params
func (o *GetBetaSystemInformationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetBetaSystemInformationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
