// Code generated by go-swagger; DO NOT EDIT.

package lifecycle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutLifecycleBounceParams creates a new PutLifecycleBounceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutLifecycleBounceParams() *PutLifecycleBounceParams {
	return &PutLifecycleBounceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutLifecycleBounceParamsWithTimeout creates a new PutLifecycleBounceParams object
// with the ability to set a timeout on a request.
func NewPutLifecycleBounceParamsWithTimeout(timeout time.Duration) *PutLifecycleBounceParams {
	return &PutLifecycleBounceParams{
		timeout: timeout,
	}
}

// NewPutLifecycleBounceParamsWithContext creates a new PutLifecycleBounceParams object
// with the ability to set a context for a request.
func NewPutLifecycleBounceParamsWithContext(ctx context.Context) *PutLifecycleBounceParams {
	return &PutLifecycleBounceParams{
		Context: ctx,
	}
}

// NewPutLifecycleBounceParamsWithHTTPClient creates a new PutLifecycleBounceParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutLifecycleBounceParamsWithHTTPClient(client *http.Client) *PutLifecycleBounceParams {
	return &PutLifecycleBounceParams{
		HTTPClient: client,
	}
}

/*
PutLifecycleBounceParams contains all the parameters to send to the API endpoint

	for the put lifecycle bounce operation.

	Typically these are written to a http.Request.
*/
type PutLifecycleBounceParams struct {

	/* Body.

	   The phase to bounce
	*/
	Body string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put lifecycle bounce params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutLifecycleBounceParams) WithDefaults() *PutLifecycleBounceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put lifecycle bounce params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutLifecycleBounceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put lifecycle bounce params
func (o *PutLifecycleBounceParams) WithTimeout(timeout time.Duration) *PutLifecycleBounceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put lifecycle bounce params
func (o *PutLifecycleBounceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put lifecycle bounce params
func (o *PutLifecycleBounceParams) WithContext(ctx context.Context) *PutLifecycleBounceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put lifecycle bounce params
func (o *PutLifecycleBounceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put lifecycle bounce params
func (o *PutLifecycleBounceParams) WithHTTPClient(client *http.Client) *PutLifecycleBounceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put lifecycle bounce params
func (o *PutLifecycleBounceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put lifecycle bounce params
func (o *PutLifecycleBounceParams) WithBody(body string) *PutLifecycleBounceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put lifecycle bounce params
func (o *PutLifecycleBounceParams) SetBody(body string) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PutLifecycleBounceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
