// Code generated by go-swagger; DO NOT EDIT.

package script

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/dmji/go-nexus/models"
)

// NewPutScriptByNameParams creates a new PutScriptByNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutScriptByNameParams() *PutScriptByNameParams {
	return &PutScriptByNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutScriptByNameParamsWithTimeout creates a new PutScriptByNameParams object
// with the ability to set a timeout on a request.
func NewPutScriptByNameParamsWithTimeout(timeout time.Duration) *PutScriptByNameParams {
	return &PutScriptByNameParams{
		timeout: timeout,
	}
}

// NewPutScriptByNameParamsWithContext creates a new PutScriptByNameParams object
// with the ability to set a context for a request.
func NewPutScriptByNameParamsWithContext(ctx context.Context) *PutScriptByNameParams {
	return &PutScriptByNameParams{
		Context: ctx,
	}
}

// NewPutScriptByNameParamsWithHTTPClient creates a new PutScriptByNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutScriptByNameParamsWithHTTPClient(client *http.Client) *PutScriptByNameParams {
	return &PutScriptByNameParams{
		HTTPClient: client,
	}
}

/*
PutScriptByNameParams contains all the parameters to send to the API endpoint

	for the put script by name operation.

	Typically these are written to a http.Request.
*/
type PutScriptByNameParams struct {

	// Body.
	Body *models.ScriptXO

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put script by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutScriptByNameParams) WithDefaults() *PutScriptByNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put script by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutScriptByNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put script by name params
func (o *PutScriptByNameParams) WithTimeout(timeout time.Duration) *PutScriptByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put script by name params
func (o *PutScriptByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put script by name params
func (o *PutScriptByNameParams) WithContext(ctx context.Context) *PutScriptByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put script by name params
func (o *PutScriptByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put script by name params
func (o *PutScriptByNameParams) WithHTTPClient(client *http.Client) *PutScriptByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put script by name params
func (o *PutScriptByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put script by name params
func (o *PutScriptByNameParams) WithBody(body *models.ScriptXO) *PutScriptByNameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put script by name params
func (o *PutScriptByNameParams) SetBody(body *models.ScriptXO) {
	o.Body = body
}

// WithName adds the name to the put script by name params
func (o *PutScriptByNameParams) WithName(name string) *PutScriptByNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the put script by name params
func (o *PutScriptByNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PutScriptByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
