// Code generated by go-swagger; DO NOT EDIT.

package content_selectors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dmji/go-nexus/models"
)

// GetSecurityContentSelectorsReader is a Reader for the GetSecurityContentSelectors structure.
type GetSecurityContentSelectorsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSecurityContentSelectorsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSecurityContentSelectorsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetSecurityContentSelectorsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/security/content-selectors] GetSecurityContentSelectors", response, response.Code())
	}
}

// NewGetSecurityContentSelectorsOK creates a GetSecurityContentSelectorsOK with default headers values
func NewGetSecurityContentSelectorsOK() *GetSecurityContentSelectorsOK {
	return &GetSecurityContentSelectorsOK{}
}

/*
GetSecurityContentSelectorsOK describes a response with status code 200, with default header values.

successful operation
*/
type GetSecurityContentSelectorsOK struct {
	Payload []*models.ContentSelectorAPIResponse
}

// IsSuccess returns true when this get security content selectors o k response has a 2xx status code
func (o *GetSecurityContentSelectorsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get security content selectors o k response has a 3xx status code
func (o *GetSecurityContentSelectorsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get security content selectors o k response has a 4xx status code
func (o *GetSecurityContentSelectorsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get security content selectors o k response has a 5xx status code
func (o *GetSecurityContentSelectorsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get security content selectors o k response a status code equal to that given
func (o *GetSecurityContentSelectorsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get security content selectors o k response
func (o *GetSecurityContentSelectorsOK) Code() int {
	return 200
}

func (o *GetSecurityContentSelectorsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/security/content-selectors][%d] getSecurityContentSelectorsOK %s", 200, payload)
}

func (o *GetSecurityContentSelectorsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/security/content-selectors][%d] getSecurityContentSelectorsOK %s", 200, payload)
}

func (o *GetSecurityContentSelectorsOK) GetPayload() []*models.ContentSelectorAPIResponse {
	return o.Payload
}

func (o *GetSecurityContentSelectorsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSecurityContentSelectorsForbidden creates a GetSecurityContentSelectorsForbidden with default headers values
func NewGetSecurityContentSelectorsForbidden() *GetSecurityContentSelectorsForbidden {
	return &GetSecurityContentSelectorsForbidden{}
}

/*
GetSecurityContentSelectorsForbidden describes a response with status code 403, with default header values.

Insufficient permissions to read content selectors
*/
type GetSecurityContentSelectorsForbidden struct {
}

// IsSuccess returns true when this get security content selectors forbidden response has a 2xx status code
func (o *GetSecurityContentSelectorsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get security content selectors forbidden response has a 3xx status code
func (o *GetSecurityContentSelectorsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get security content selectors forbidden response has a 4xx status code
func (o *GetSecurityContentSelectorsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get security content selectors forbidden response has a 5xx status code
func (o *GetSecurityContentSelectorsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get security content selectors forbidden response a status code equal to that given
func (o *GetSecurityContentSelectorsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get security content selectors forbidden response
func (o *GetSecurityContentSelectorsForbidden) Code() int {
	return 403
}

func (o *GetSecurityContentSelectorsForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/security/content-selectors][%d] getSecurityContentSelectorsForbidden", 403)
}

func (o *GetSecurityContentSelectorsForbidden) String() string {
	return fmt.Sprintf("[GET /v1/security/content-selectors][%d] getSecurityContentSelectorsForbidden", 403)
}

func (o *GetSecurityContentSelectorsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
