// Code generated by go-swagger; DO NOT EDIT.

package security_management_users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/dmji/go-nexus/models"
)

// NewPutSecurityUsersByUserIDParams creates a new PutSecurityUsersByUserIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutSecurityUsersByUserIDParams() *PutSecurityUsersByUserIDParams {
	return &PutSecurityUsersByUserIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutSecurityUsersByUserIDParamsWithTimeout creates a new PutSecurityUsersByUserIDParams object
// with the ability to set a timeout on a request.
func NewPutSecurityUsersByUserIDParamsWithTimeout(timeout time.Duration) *PutSecurityUsersByUserIDParams {
	return &PutSecurityUsersByUserIDParams{
		timeout: timeout,
	}
}

// NewPutSecurityUsersByUserIDParamsWithContext creates a new PutSecurityUsersByUserIDParams object
// with the ability to set a context for a request.
func NewPutSecurityUsersByUserIDParamsWithContext(ctx context.Context) *PutSecurityUsersByUserIDParams {
	return &PutSecurityUsersByUserIDParams{
		Context: ctx,
	}
}

// NewPutSecurityUsersByUserIDParamsWithHTTPClient creates a new PutSecurityUsersByUserIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutSecurityUsersByUserIDParamsWithHTTPClient(client *http.Client) *PutSecurityUsersByUserIDParams {
	return &PutSecurityUsersByUserIDParams{
		HTTPClient: client,
	}
}

/*
PutSecurityUsersByUserIDParams contains all the parameters to send to the API endpoint

	for the put security users by user Id operation.

	Typically these are written to a http.Request.
*/
type PutSecurityUsersByUserIDParams struct {

	/* Body.

	   A representation of the user to update.
	*/
	Body *models.APIUser

	/* UserID.

	   The userid the request should apply to.
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put security users by user Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutSecurityUsersByUserIDParams) WithDefaults() *PutSecurityUsersByUserIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put security users by user Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutSecurityUsersByUserIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put security users by user Id params
func (o *PutSecurityUsersByUserIDParams) WithTimeout(timeout time.Duration) *PutSecurityUsersByUserIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put security users by user Id params
func (o *PutSecurityUsersByUserIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put security users by user Id params
func (o *PutSecurityUsersByUserIDParams) WithContext(ctx context.Context) *PutSecurityUsersByUserIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put security users by user Id params
func (o *PutSecurityUsersByUserIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put security users by user Id params
func (o *PutSecurityUsersByUserIDParams) WithHTTPClient(client *http.Client) *PutSecurityUsersByUserIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put security users by user Id params
func (o *PutSecurityUsersByUserIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put security users by user Id params
func (o *PutSecurityUsersByUserIDParams) WithBody(body *models.APIUser) *PutSecurityUsersByUserIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put security users by user Id params
func (o *PutSecurityUsersByUserIDParams) SetBody(body *models.APIUser) {
	o.Body = body
}

// WithUserID adds the userID to the put security users by user Id params
func (o *PutSecurityUsersByUserIDParams) WithUserID(userID string) *PutSecurityUsersByUserIDParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the put security users by user Id params
func (o *PutSecurityUsersByUserIDParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *PutSecurityUsersByUserIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
