// Code generated by go-swagger; DO NOT EDIT.

package manage_sonatype_repository_firewall_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostIqEnableReader is a Reader for the PostIqEnable structure.
type PostIqEnableReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostIqEnableReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPostIqEnableNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostIqEnableBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/iq/enable] PostIqEnable", response, response.Code())
	}
}

// NewPostIqEnableNoContent creates a PostIqEnableNoContent with default headers values
func NewPostIqEnableNoContent() *PostIqEnableNoContent {
	return &PostIqEnableNoContent{}
}

/*
PostIqEnableNoContent describes a response with status code 204, with default header values.

Sonatype Repository Firewall has been enabled
*/
type PostIqEnableNoContent struct {
}

// IsSuccess returns true when this post iq enable no content response has a 2xx status code
func (o *PostIqEnableNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post iq enable no content response has a 3xx status code
func (o *PostIqEnableNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post iq enable no content response has a 4xx status code
func (o *PostIqEnableNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post iq enable no content response has a 5xx status code
func (o *PostIqEnableNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post iq enable no content response a status code equal to that given
func (o *PostIqEnableNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post iq enable no content response
func (o *PostIqEnableNoContent) Code() int {
	return 204
}

func (o *PostIqEnableNoContent) Error() string {
	return fmt.Sprintf("[POST /v1/iq/enable][%d] postIqEnableNoContent", 204)
}

func (o *PostIqEnableNoContent) String() string {
	return fmt.Sprintf("[POST /v1/iq/enable][%d] postIqEnableNoContent", 204)
}

func (o *PostIqEnableNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostIqEnableBadRequest creates a PostIqEnableBadRequest with default headers values
func NewPostIqEnableBadRequest() *PostIqEnableBadRequest {
	return &PostIqEnableBadRequest{}
}

/*
PostIqEnableBadRequest describes a response with status code 400, with default header values.

Sonatype Repository Firewall connection not configured
*/
type PostIqEnableBadRequest struct {
}

// IsSuccess returns true when this post iq enable bad request response has a 2xx status code
func (o *PostIqEnableBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post iq enable bad request response has a 3xx status code
func (o *PostIqEnableBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post iq enable bad request response has a 4xx status code
func (o *PostIqEnableBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post iq enable bad request response has a 5xx status code
func (o *PostIqEnableBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post iq enable bad request response a status code equal to that given
func (o *PostIqEnableBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post iq enable bad request response
func (o *PostIqEnableBadRequest) Code() int {
	return 400
}

func (o *PostIqEnableBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/iq/enable][%d] postIqEnableBadRequest", 400)
}

func (o *PostIqEnableBadRequest) String() string {
	return fmt.Sprintf("[POST /v1/iq/enable][%d] postIqEnableBadRequest", 400)
}

func (o *PostIqEnableBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
