// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostTasksByIDStopReader is a Reader for the PostTasksByIDStop structure.
type PostTasksByIDStopReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostTasksByIDStopReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPostTasksByIDStopNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewPostTasksByIDStopNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostTasksByIDStopConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/tasks/{id}/stop] PostTasksByIdStop", response, response.Code())
	}
}

// NewPostTasksByIDStopNoContent creates a PostTasksByIDStopNoContent with default headers values
func NewPostTasksByIDStopNoContent() *PostTasksByIDStopNoContent {
	return &PostTasksByIDStopNoContent{}
}

/*
PostTasksByIDStopNoContent describes a response with status code 204, with default header values.

Task was stopped
*/
type PostTasksByIDStopNoContent struct {
}

// IsSuccess returns true when this post tasks by Id stop no content response has a 2xx status code
func (o *PostTasksByIDStopNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post tasks by Id stop no content response has a 3xx status code
func (o *PostTasksByIDStopNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post tasks by Id stop no content response has a 4xx status code
func (o *PostTasksByIDStopNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post tasks by Id stop no content response has a 5xx status code
func (o *PostTasksByIDStopNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post tasks by Id stop no content response a status code equal to that given
func (o *PostTasksByIDStopNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post tasks by Id stop no content response
func (o *PostTasksByIDStopNoContent) Code() int {
	return 204
}

func (o *PostTasksByIDStopNoContent) Error() string {
	return fmt.Sprintf("[POST /v1/tasks/{id}/stop][%d] postTasksByIdStopNoContent", 204)
}

func (o *PostTasksByIDStopNoContent) String() string {
	return fmt.Sprintf("[POST /v1/tasks/{id}/stop][%d] postTasksByIdStopNoContent", 204)
}

func (o *PostTasksByIDStopNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostTasksByIDStopNotFound creates a PostTasksByIDStopNotFound with default headers values
func NewPostTasksByIDStopNotFound() *PostTasksByIDStopNotFound {
	return &PostTasksByIDStopNotFound{}
}

/*
PostTasksByIDStopNotFound describes a response with status code 404, with default header values.

Task not found
*/
type PostTasksByIDStopNotFound struct {
}

// IsSuccess returns true when this post tasks by Id stop not found response has a 2xx status code
func (o *PostTasksByIDStopNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post tasks by Id stop not found response has a 3xx status code
func (o *PostTasksByIDStopNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post tasks by Id stop not found response has a 4xx status code
func (o *PostTasksByIDStopNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post tasks by Id stop not found response has a 5xx status code
func (o *PostTasksByIDStopNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post tasks by Id stop not found response a status code equal to that given
func (o *PostTasksByIDStopNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the post tasks by Id stop not found response
func (o *PostTasksByIDStopNotFound) Code() int {
	return 404
}

func (o *PostTasksByIDStopNotFound) Error() string {
	return fmt.Sprintf("[POST /v1/tasks/{id}/stop][%d] postTasksByIdStopNotFound", 404)
}

func (o *PostTasksByIDStopNotFound) String() string {
	return fmt.Sprintf("[POST /v1/tasks/{id}/stop][%d] postTasksByIdStopNotFound", 404)
}

func (o *PostTasksByIDStopNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostTasksByIDStopConflict creates a PostTasksByIDStopConflict with default headers values
func NewPostTasksByIDStopConflict() *PostTasksByIDStopConflict {
	return &PostTasksByIDStopConflict{}
}

/*
PostTasksByIDStopConflict describes a response with status code 409, with default header values.

Unable to stop task
*/
type PostTasksByIDStopConflict struct {
}

// IsSuccess returns true when this post tasks by Id stop conflict response has a 2xx status code
func (o *PostTasksByIDStopConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post tasks by Id stop conflict response has a 3xx status code
func (o *PostTasksByIDStopConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post tasks by Id stop conflict response has a 4xx status code
func (o *PostTasksByIDStopConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this post tasks by Id stop conflict response has a 5xx status code
func (o *PostTasksByIDStopConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this post tasks by Id stop conflict response a status code equal to that given
func (o *PostTasksByIDStopConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the post tasks by Id stop conflict response
func (o *PostTasksByIDStopConflict) Code() int {
	return 409
}

func (o *PostTasksByIDStopConflict) Error() string {
	return fmt.Sprintf("[POST /v1/tasks/{id}/stop][%d] postTasksByIdStopConflict", 409)
}

func (o *PostTasksByIDStopConflict) String() string {
	return fmt.Sprintf("[POST /v1/tasks/{id}/stop][%d] postTasksByIdStopConflict", 409)
}

func (o *PostTasksByIDStopConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
