// Code generated by go-swagger; DO NOT EDIT.

package blob_store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteBlobstoresByNameReader is a Reader for the DeleteBlobstoresByName structure.
type DeleteBlobstoresByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteBlobstoresByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewDeleteBlobstoresByNameDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewDeleteBlobstoresByNameDefault creates a DeleteBlobstoresByNameDefault with default headers values
func NewDeleteBlobstoresByNameDefault(code int) *DeleteBlobstoresByNameDefault {
	return &DeleteBlobstoresByNameDefault{
		_statusCode: code,
	}
}

/*
DeleteBlobstoresByNameDefault describes a response with status code -1, with default header values.

successful operation
*/
type DeleteBlobstoresByNameDefault struct {
	_statusCode int
}

// IsSuccess returns true when this delete blobstores by name default response has a 2xx status code
func (o *DeleteBlobstoresByNameDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete blobstores by name default response has a 3xx status code
func (o *DeleteBlobstoresByNameDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete blobstores by name default response has a 4xx status code
func (o *DeleteBlobstoresByNameDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete blobstores by name default response has a 5xx status code
func (o *DeleteBlobstoresByNameDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete blobstores by name default response a status code equal to that given
func (o *DeleteBlobstoresByNameDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete blobstores by name default response
func (o *DeleteBlobstoresByNameDefault) Code() int {
	return o._statusCode
}

func (o *DeleteBlobstoresByNameDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/blobstores/{name}][%d] DeleteBlobstoresByName default", o._statusCode)
}

func (o *DeleteBlobstoresByNameDefault) String() string {
	return fmt.Sprintf("[DELETE /v1/blobstores/{name}][%d] DeleteBlobstoresByName default", o._statusCode)
}

func (o *DeleteBlobstoresByNameDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
