// Code generated by go-swagger; DO NOT EDIT.

package blob_store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dmji/go-nexus/models"
)

// GetBlobStore2Reader is a Reader for the GetBlobStore2 structure.
type GetBlobStore2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBlobStore2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBlobStore2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetBlobStore2Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetBlobStore2Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetBlobStore2NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/blobstores/google/{name}] getBlobStore_2", response, response.Code())
	}
}

// NewGetBlobStore2OK creates a GetBlobStore2OK with default headers values
func NewGetBlobStore2OK() *GetBlobStore2OK {
	return &GetBlobStore2OK{}
}

/*
GetBlobStore2OK describes a response with status code 200, with default header values.

Google Cloud blob store configuration
*/
type GetBlobStore2OK struct {
	Payload *models.GoogleCloudBlobstoreAPIModel
}

// IsSuccess returns true when this get blob store2 o k response has a 2xx status code
func (o *GetBlobStore2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get blob store2 o k response has a 3xx status code
func (o *GetBlobStore2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get blob store2 o k response has a 4xx status code
func (o *GetBlobStore2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get blob store2 o k response has a 5xx status code
func (o *GetBlobStore2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this get blob store2 o k response a status code equal to that given
func (o *GetBlobStore2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get blob store2 o k response
func (o *GetBlobStore2OK) Code() int {
	return 200
}

func (o *GetBlobStore2OK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/blobstores/google/{name}][%d] getBlobStore2OK %s", 200, payload)
}

func (o *GetBlobStore2OK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/blobstores/google/{name}][%d] getBlobStore2OK %s", 200, payload)
}

func (o *GetBlobStore2OK) GetPayload() *models.GoogleCloudBlobstoreAPIModel {
	return o.Payload
}

func (o *GetBlobStore2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GoogleCloudBlobstoreAPIModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBlobStore2Unauthorized creates a GetBlobStore2Unauthorized with default headers values
func NewGetBlobStore2Unauthorized() *GetBlobStore2Unauthorized {
	return &GetBlobStore2Unauthorized{}
}

/*
GetBlobStore2Unauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type GetBlobStore2Unauthorized struct {
}

// IsSuccess returns true when this get blob store2 unauthorized response has a 2xx status code
func (o *GetBlobStore2Unauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get blob store2 unauthorized response has a 3xx status code
func (o *GetBlobStore2Unauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get blob store2 unauthorized response has a 4xx status code
func (o *GetBlobStore2Unauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get blob store2 unauthorized response has a 5xx status code
func (o *GetBlobStore2Unauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get blob store2 unauthorized response a status code equal to that given
func (o *GetBlobStore2Unauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get blob store2 unauthorized response
func (o *GetBlobStore2Unauthorized) Code() int {
	return 401
}

func (o *GetBlobStore2Unauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/blobstores/google/{name}][%d] getBlobStore2Unauthorized", 401)
}

func (o *GetBlobStore2Unauthorized) String() string {
	return fmt.Sprintf("[GET /v1/blobstores/google/{name}][%d] getBlobStore2Unauthorized", 401)
}

func (o *GetBlobStore2Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetBlobStore2Forbidden creates a GetBlobStore2Forbidden with default headers values
func NewGetBlobStore2Forbidden() *GetBlobStore2Forbidden {
	return &GetBlobStore2Forbidden{}
}

/*
GetBlobStore2Forbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type GetBlobStore2Forbidden struct {
}

// IsSuccess returns true when this get blob store2 forbidden response has a 2xx status code
func (o *GetBlobStore2Forbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get blob store2 forbidden response has a 3xx status code
func (o *GetBlobStore2Forbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get blob store2 forbidden response has a 4xx status code
func (o *GetBlobStore2Forbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get blob store2 forbidden response has a 5xx status code
func (o *GetBlobStore2Forbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get blob store2 forbidden response a status code equal to that given
func (o *GetBlobStore2Forbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get blob store2 forbidden response
func (o *GetBlobStore2Forbidden) Code() int {
	return 403
}

func (o *GetBlobStore2Forbidden) Error() string {
	return fmt.Sprintf("[GET /v1/blobstores/google/{name}][%d] getBlobStore2Forbidden", 403)
}

func (o *GetBlobStore2Forbidden) String() string {
	return fmt.Sprintf("[GET /v1/blobstores/google/{name}][%d] getBlobStore2Forbidden", 403)
}

func (o *GetBlobStore2Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetBlobStore2NotFound creates a GetBlobStore2NotFound with default headers values
func NewGetBlobStore2NotFound() *GetBlobStore2NotFound {
	return &GetBlobStore2NotFound{}
}

/*
GetBlobStore2NotFound describes a response with status code 404, with default header values.

Repository not found
*/
type GetBlobStore2NotFound struct {
}

// IsSuccess returns true when this get blob store2 not found response has a 2xx status code
func (o *GetBlobStore2NotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get blob store2 not found response has a 3xx status code
func (o *GetBlobStore2NotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get blob store2 not found response has a 4xx status code
func (o *GetBlobStore2NotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get blob store2 not found response has a 5xx status code
func (o *GetBlobStore2NotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get blob store2 not found response a status code equal to that given
func (o *GetBlobStore2NotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get blob store2 not found response
func (o *GetBlobStore2NotFound) Code() int {
	return 404
}

func (o *GetBlobStore2NotFound) Error() string {
	return fmt.Sprintf("[GET /v1/blobstores/google/{name}][%d] getBlobStore2NotFound", 404)
}

func (o *GetBlobStore2NotFound) String() string {
	return fmt.Sprintf("[GET /v1/blobstores/google/{name}][%d] getBlobStore2NotFound", 404)
}

func (o *GetBlobStore2NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
