// Code generated by go-swagger; DO NOT EDIT.

package blob_store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetBlobstoresGoogleRegionsByProjectIDReader is a Reader for the GetBlobstoresGoogleRegionsByProjectID structure.
type GetBlobstoresGoogleRegionsByProjectIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBlobstoresGoogleRegionsByProjectIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBlobstoresGoogleRegionsByProjectIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetBlobstoresGoogleRegionsByProjectIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetBlobstoresGoogleRegionsByProjectIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetBlobstoresGoogleRegionsByProjectIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/blobstores/google/regions/{projectId}] GetBlobstoresGoogleRegionsByProjectId", response, response.Code())
	}
}

// NewGetBlobstoresGoogleRegionsByProjectIDOK creates a GetBlobstoresGoogleRegionsByProjectIDOK with default headers values
func NewGetBlobstoresGoogleRegionsByProjectIDOK() *GetBlobstoresGoogleRegionsByProjectIDOK {
	return &GetBlobstoresGoogleRegionsByProjectIDOK{}
}

/*
GetBlobstoresGoogleRegionsByProjectIDOK describes a response with status code 200, with default header values.

List of regions found
*/
type GetBlobstoresGoogleRegionsByProjectIDOK struct {
	Payload []string
}

// IsSuccess returns true when this get blobstores google regions by project Id o k response has a 2xx status code
func (o *GetBlobstoresGoogleRegionsByProjectIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get blobstores google regions by project Id o k response has a 3xx status code
func (o *GetBlobstoresGoogleRegionsByProjectIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get blobstores google regions by project Id o k response has a 4xx status code
func (o *GetBlobstoresGoogleRegionsByProjectIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get blobstores google regions by project Id o k response has a 5xx status code
func (o *GetBlobstoresGoogleRegionsByProjectIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get blobstores google regions by project Id o k response a status code equal to that given
func (o *GetBlobstoresGoogleRegionsByProjectIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get blobstores google regions by project Id o k response
func (o *GetBlobstoresGoogleRegionsByProjectIDOK) Code() int {
	return 200
}

func (o *GetBlobstoresGoogleRegionsByProjectIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/blobstores/google/regions/{projectId}][%d] getBlobstoresGoogleRegionsByProjectIdOK %s", 200, payload)
}

func (o *GetBlobstoresGoogleRegionsByProjectIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/blobstores/google/regions/{projectId}][%d] getBlobstoresGoogleRegionsByProjectIdOK %s", 200, payload)
}

func (o *GetBlobstoresGoogleRegionsByProjectIDOK) GetPayload() []string {
	return o.Payload
}

func (o *GetBlobstoresGoogleRegionsByProjectIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBlobstoresGoogleRegionsByProjectIDUnauthorized creates a GetBlobstoresGoogleRegionsByProjectIDUnauthorized with default headers values
func NewGetBlobstoresGoogleRegionsByProjectIDUnauthorized() *GetBlobstoresGoogleRegionsByProjectIDUnauthorized {
	return &GetBlobstoresGoogleRegionsByProjectIDUnauthorized{}
}

/*
GetBlobstoresGoogleRegionsByProjectIDUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type GetBlobstoresGoogleRegionsByProjectIDUnauthorized struct {
}

// IsSuccess returns true when this get blobstores google regions by project Id unauthorized response has a 2xx status code
func (o *GetBlobstoresGoogleRegionsByProjectIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get blobstores google regions by project Id unauthorized response has a 3xx status code
func (o *GetBlobstoresGoogleRegionsByProjectIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get blobstores google regions by project Id unauthorized response has a 4xx status code
func (o *GetBlobstoresGoogleRegionsByProjectIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get blobstores google regions by project Id unauthorized response has a 5xx status code
func (o *GetBlobstoresGoogleRegionsByProjectIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get blobstores google regions by project Id unauthorized response a status code equal to that given
func (o *GetBlobstoresGoogleRegionsByProjectIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get blobstores google regions by project Id unauthorized response
func (o *GetBlobstoresGoogleRegionsByProjectIDUnauthorized) Code() int {
	return 401
}

func (o *GetBlobstoresGoogleRegionsByProjectIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/blobstores/google/regions/{projectId}][%d] getBlobstoresGoogleRegionsByProjectIdUnauthorized", 401)
}

func (o *GetBlobstoresGoogleRegionsByProjectIDUnauthorized) String() string {
	return fmt.Sprintf("[GET /v1/blobstores/google/regions/{projectId}][%d] getBlobstoresGoogleRegionsByProjectIdUnauthorized", 401)
}

func (o *GetBlobstoresGoogleRegionsByProjectIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetBlobstoresGoogleRegionsByProjectIDForbidden creates a GetBlobstoresGoogleRegionsByProjectIDForbidden with default headers values
func NewGetBlobstoresGoogleRegionsByProjectIDForbidden() *GetBlobstoresGoogleRegionsByProjectIDForbidden {
	return &GetBlobstoresGoogleRegionsByProjectIDForbidden{}
}

/*
GetBlobstoresGoogleRegionsByProjectIDForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type GetBlobstoresGoogleRegionsByProjectIDForbidden struct {
}

// IsSuccess returns true when this get blobstores google regions by project Id forbidden response has a 2xx status code
func (o *GetBlobstoresGoogleRegionsByProjectIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get blobstores google regions by project Id forbidden response has a 3xx status code
func (o *GetBlobstoresGoogleRegionsByProjectIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get blobstores google regions by project Id forbidden response has a 4xx status code
func (o *GetBlobstoresGoogleRegionsByProjectIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get blobstores google regions by project Id forbidden response has a 5xx status code
func (o *GetBlobstoresGoogleRegionsByProjectIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get blobstores google regions by project Id forbidden response a status code equal to that given
func (o *GetBlobstoresGoogleRegionsByProjectIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get blobstores google regions by project Id forbidden response
func (o *GetBlobstoresGoogleRegionsByProjectIDForbidden) Code() int {
	return 403
}

func (o *GetBlobstoresGoogleRegionsByProjectIDForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/blobstores/google/regions/{projectId}][%d] getBlobstoresGoogleRegionsByProjectIdForbidden", 403)
}

func (o *GetBlobstoresGoogleRegionsByProjectIDForbidden) String() string {
	return fmt.Sprintf("[GET /v1/blobstores/google/regions/{projectId}][%d] getBlobstoresGoogleRegionsByProjectIdForbidden", 403)
}

func (o *GetBlobstoresGoogleRegionsByProjectIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetBlobstoresGoogleRegionsByProjectIDNotFound creates a GetBlobstoresGoogleRegionsByProjectIDNotFound with default headers values
func NewGetBlobstoresGoogleRegionsByProjectIDNotFound() *GetBlobstoresGoogleRegionsByProjectIDNotFound {
	return &GetBlobstoresGoogleRegionsByProjectIDNotFound{}
}

/*
GetBlobstoresGoogleRegionsByProjectIDNotFound describes a response with status code 404, with default header values.

Project not found
*/
type GetBlobstoresGoogleRegionsByProjectIDNotFound struct {
}

// IsSuccess returns true when this get blobstores google regions by project Id not found response has a 2xx status code
func (o *GetBlobstoresGoogleRegionsByProjectIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get blobstores google regions by project Id not found response has a 3xx status code
func (o *GetBlobstoresGoogleRegionsByProjectIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get blobstores google regions by project Id not found response has a 4xx status code
func (o *GetBlobstoresGoogleRegionsByProjectIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get blobstores google regions by project Id not found response has a 5xx status code
func (o *GetBlobstoresGoogleRegionsByProjectIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get blobstores google regions by project Id not found response a status code equal to that given
func (o *GetBlobstoresGoogleRegionsByProjectIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get blobstores google regions by project Id not found response
func (o *GetBlobstoresGoogleRegionsByProjectIDNotFound) Code() int {
	return 404
}

func (o *GetBlobstoresGoogleRegionsByProjectIDNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/blobstores/google/regions/{projectId}][%d] getBlobstoresGoogleRegionsByProjectIdNotFound", 404)
}

func (o *GetBlobstoresGoogleRegionsByProjectIDNotFound) String() string {
	return fmt.Sprintf("[GET /v1/blobstores/google/regions/{projectId}][%d] getBlobstoresGoogleRegionsByProjectIdNotFound", 404)
}

func (o *GetBlobstoresGoogleRegionsByProjectIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
