// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dmji/go-nexus/models"
)

// GetRepositoriesP2ProxyByRepositorynameReader is a Reader for the GetRepositoriesP2ProxyByRepositoryname structure.
type GetRepositoriesP2ProxyByRepositorynameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRepositoriesP2ProxyByRepositorynameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRepositoriesP2ProxyByRepositorynameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/repositories/p2/proxy/{repositoryName}] GetRepositoriesP2ProxyByRepositoryname", response, response.Code())
	}
}

// NewGetRepositoriesP2ProxyByRepositorynameOK creates a GetRepositoriesP2ProxyByRepositorynameOK with default headers values
func NewGetRepositoriesP2ProxyByRepositorynameOK() *GetRepositoriesP2ProxyByRepositorynameOK {
	return &GetRepositoriesP2ProxyByRepositorynameOK{}
}

/*
GetRepositoriesP2ProxyByRepositorynameOK describes a response with status code 200, with default header values.

successful operation
*/
type GetRepositoriesP2ProxyByRepositorynameOK struct {
	Payload *models.SimpleAPIProxyRepository
}

// IsSuccess returns true when this get repositories p2 proxy by repositoryname o k response has a 2xx status code
func (o *GetRepositoriesP2ProxyByRepositorynameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get repositories p2 proxy by repositoryname o k response has a 3xx status code
func (o *GetRepositoriesP2ProxyByRepositorynameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get repositories p2 proxy by repositoryname o k response has a 4xx status code
func (o *GetRepositoriesP2ProxyByRepositorynameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get repositories p2 proxy by repositoryname o k response has a 5xx status code
func (o *GetRepositoriesP2ProxyByRepositorynameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get repositories p2 proxy by repositoryname o k response a status code equal to that given
func (o *GetRepositoriesP2ProxyByRepositorynameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get repositories p2 proxy by repositoryname o k response
func (o *GetRepositoriesP2ProxyByRepositorynameOK) Code() int {
	return 200
}

func (o *GetRepositoriesP2ProxyByRepositorynameOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/repositories/p2/proxy/{repositoryName}][%d] getRepositoriesP2ProxyByRepositorynameOK %s", 200, payload)
}

func (o *GetRepositoriesP2ProxyByRepositorynameOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/repositories/p2/proxy/{repositoryName}][%d] getRepositoriesP2ProxyByRepositorynameOK %s", 200, payload)
}

func (o *GetRepositoriesP2ProxyByRepositorynameOK) GetPayload() *models.SimpleAPIProxyRepository {
	return o.Payload
}

func (o *GetRepositoriesP2ProxyByRepositorynameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimpleAPIProxyRepository)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
