// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dmji/go-nexus/models"
)

// GetRepositoriesRubygemsHostedByRepositoryNameReader is a Reader for the GetRepositoriesRubygemsHostedByRepositoryName structure.
type GetRepositoriesRubygemsHostedByRepositoryNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRepositoriesRubygemsHostedByRepositoryNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRepositoriesRubygemsHostedByRepositoryNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/repositories/rubygems/hosted/{repositoryName}] GetRepositoriesRubygemsHostedByRepositoryName", response, response.Code())
	}
}

// NewGetRepositoriesRubygemsHostedByRepositoryNameOK creates a GetRepositoriesRubygemsHostedByRepositoryNameOK with default headers values
func NewGetRepositoriesRubygemsHostedByRepositoryNameOK() *GetRepositoriesRubygemsHostedByRepositoryNameOK {
	return &GetRepositoriesRubygemsHostedByRepositoryNameOK{}
}

/*
GetRepositoriesRubygemsHostedByRepositoryNameOK describes a response with status code 200, with default header values.

successful operation
*/
type GetRepositoriesRubygemsHostedByRepositoryNameOK struct {
	Payload *models.SimpleAPIHostedRepository
}

// IsSuccess returns true when this get repositories rubygems hosted by repository name o k response has a 2xx status code
func (o *GetRepositoriesRubygemsHostedByRepositoryNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get repositories rubygems hosted by repository name o k response has a 3xx status code
func (o *GetRepositoriesRubygemsHostedByRepositoryNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get repositories rubygems hosted by repository name o k response has a 4xx status code
func (o *GetRepositoriesRubygemsHostedByRepositoryNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get repositories rubygems hosted by repository name o k response has a 5xx status code
func (o *GetRepositoriesRubygemsHostedByRepositoryNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get repositories rubygems hosted by repository name o k response a status code equal to that given
func (o *GetRepositoriesRubygemsHostedByRepositoryNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get repositories rubygems hosted by repository name o k response
func (o *GetRepositoriesRubygemsHostedByRepositoryNameOK) Code() int {
	return 200
}

func (o *GetRepositoriesRubygemsHostedByRepositoryNameOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/repositories/rubygems/hosted/{repositoryName}][%d] getRepositoriesRubygemsHostedByRepositoryNameOK %s", 200, payload)
}

func (o *GetRepositoriesRubygemsHostedByRepositoryNameOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/repositories/rubygems/hosted/{repositoryName}][%d] getRepositoriesRubygemsHostedByRepositoryNameOK %s", 200, payload)
}

func (o *GetRepositoriesRubygemsHostedByRepositoryNameOK) GetPayload() *models.SimpleAPIHostedRepository {
	return o.Payload
}

func (o *GetRepositoriesRubygemsHostedByRepositoryNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimpleAPIHostedRepository)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
