// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRepositoriesAptHostedByRepositoryNameParams creates a new GetRepositoriesAptHostedByRepositoryNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRepositoriesAptHostedByRepositoryNameParams() *GetRepositoriesAptHostedByRepositoryNameParams {
	return &GetRepositoriesAptHostedByRepositoryNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRepositoriesAptHostedByRepositoryNameParamsWithTimeout creates a new GetRepositoriesAptHostedByRepositoryNameParams object
// with the ability to set a timeout on a request.
func NewGetRepositoriesAptHostedByRepositoryNameParamsWithTimeout(timeout time.Duration) *GetRepositoriesAptHostedByRepositoryNameParams {
	return &GetRepositoriesAptHostedByRepositoryNameParams{
		timeout: timeout,
	}
}

// NewGetRepositoriesAptHostedByRepositoryNameParamsWithContext creates a new GetRepositoriesAptHostedByRepositoryNameParams object
// with the ability to set a context for a request.
func NewGetRepositoriesAptHostedByRepositoryNameParamsWithContext(ctx context.Context) *GetRepositoriesAptHostedByRepositoryNameParams {
	return &GetRepositoriesAptHostedByRepositoryNameParams{
		Context: ctx,
	}
}

// NewGetRepositoriesAptHostedByRepositoryNameParamsWithHTTPClient creates a new GetRepositoriesAptHostedByRepositoryNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRepositoriesAptHostedByRepositoryNameParamsWithHTTPClient(client *http.Client) *GetRepositoriesAptHostedByRepositoryNameParams {
	return &GetRepositoriesAptHostedByRepositoryNameParams{
		HTTPClient: client,
	}
}

/*
GetRepositoriesAptHostedByRepositoryNameParams contains all the parameters to send to the API endpoint

	for the get repositories apt hosted by repository name operation.

	Typically these are written to a http.Request.
*/
type GetRepositoriesAptHostedByRepositoryNameParams struct {

	// RepositoryName.
	RepositoryName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get repositories apt hosted by repository name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRepositoriesAptHostedByRepositoryNameParams) WithDefaults() *GetRepositoriesAptHostedByRepositoryNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get repositories apt hosted by repository name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRepositoriesAptHostedByRepositoryNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get repositories apt hosted by repository name params
func (o *GetRepositoriesAptHostedByRepositoryNameParams) WithTimeout(timeout time.Duration) *GetRepositoriesAptHostedByRepositoryNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repositories apt hosted by repository name params
func (o *GetRepositoriesAptHostedByRepositoryNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repositories apt hosted by repository name params
func (o *GetRepositoriesAptHostedByRepositoryNameParams) WithContext(ctx context.Context) *GetRepositoriesAptHostedByRepositoryNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repositories apt hosted by repository name params
func (o *GetRepositoriesAptHostedByRepositoryNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repositories apt hosted by repository name params
func (o *GetRepositoriesAptHostedByRepositoryNameParams) WithHTTPClient(client *http.Client) *GetRepositoriesAptHostedByRepositoryNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repositories apt hosted by repository name params
func (o *GetRepositoriesAptHostedByRepositoryNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepositoryName adds the repositoryName to the get repositories apt hosted by repository name params
func (o *GetRepositoriesAptHostedByRepositoryNameParams) WithRepositoryName(repositoryName string) *GetRepositoriesAptHostedByRepositoryNameParams {
	o.SetRepositoryName(repositoryName)
	return o
}

// SetRepositoryName adds the repositoryName to the get repositories apt hosted by repository name params
func (o *GetRepositoriesAptHostedByRepositoryNameParams) SetRepositoryName(repositoryName string) {
	o.RepositoryName = repositoryName
}

// WriteToRequest writes these params to a swagger request
func (o *GetRepositoriesAptHostedByRepositoryNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repositoryName
	if err := r.SetPathParam("repositoryName", o.RepositoryName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
