// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"nexus/models"
)

// GetRepository43Reader is a Reader for the GetRepository43 structure.
type GetRepository43Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRepository43Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRepository43OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/repositories/yum/group/{repositoryName}] getRepository_43", response, response.Code())
	}
}

// NewGetRepository43OK creates a GetRepository43OK with default headers values
func NewGetRepository43OK() *GetRepository43OK {
	return &GetRepository43OK{}
}

/*
GetRepository43OK describes a response with status code 200, with default header values.

successful operation
*/
type GetRepository43OK struct {
	Payload *models.SimpleAPIGroupRepository
}

// IsSuccess returns true when this get repository43 o k response has a 2xx status code
func (o *GetRepository43OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get repository43 o k response has a 3xx status code
func (o *GetRepository43OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get repository43 o k response has a 4xx status code
func (o *GetRepository43OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get repository43 o k response has a 5xx status code
func (o *GetRepository43OK) IsServerError() bool {
	return false
}

// IsCode returns true when this get repository43 o k response a status code equal to that given
func (o *GetRepository43OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get repository43 o k response
func (o *GetRepository43OK) Code() int {
	return 200
}

func (o *GetRepository43OK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/repositories/yum/group/{repositoryName}][%d] getRepository43OK %s", 200, payload)
}

func (o *GetRepository43OK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/repositories/yum/group/{repositoryName}][%d] getRepository43OK %s", 200, payload)
}

func (o *GetRepository43OK) GetPayload() *models.SimpleAPIGroupRepository {
	return o.Payload
}

func (o *GetRepository43OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimpleAPIGroupRepository)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
