// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRepositoriesP2ProxyByRepositorynameParams creates a new GetRepositoriesP2ProxyByRepositorynameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRepositoriesP2ProxyByRepositorynameParams() *GetRepositoriesP2ProxyByRepositorynameParams {
	return &GetRepositoriesP2ProxyByRepositorynameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRepositoriesP2ProxyByRepositorynameParamsWithTimeout creates a new GetRepositoriesP2ProxyByRepositorynameParams object
// with the ability to set a timeout on a request.
func NewGetRepositoriesP2ProxyByRepositorynameParamsWithTimeout(timeout time.Duration) *GetRepositoriesP2ProxyByRepositorynameParams {
	return &GetRepositoriesP2ProxyByRepositorynameParams{
		timeout: timeout,
	}
}

// NewGetRepositoriesP2ProxyByRepositorynameParamsWithContext creates a new GetRepositoriesP2ProxyByRepositorynameParams object
// with the ability to set a context for a request.
func NewGetRepositoriesP2ProxyByRepositorynameParamsWithContext(ctx context.Context) *GetRepositoriesP2ProxyByRepositorynameParams {
	return &GetRepositoriesP2ProxyByRepositorynameParams{
		Context: ctx,
	}
}

// NewGetRepositoriesP2ProxyByRepositorynameParamsWithHTTPClient creates a new GetRepositoriesP2ProxyByRepositorynameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRepositoriesP2ProxyByRepositorynameParamsWithHTTPClient(client *http.Client) *GetRepositoriesP2ProxyByRepositorynameParams {
	return &GetRepositoriesP2ProxyByRepositorynameParams{
		HTTPClient: client,
	}
}

/*
GetRepositoriesP2ProxyByRepositorynameParams contains all the parameters to send to the API endpoint

	for the get repositories p2 proxy by repositoryname operation.

	Typically these are written to a http.Request.
*/
type GetRepositoriesP2ProxyByRepositorynameParams struct {

	// RepositoryName.
	RepositoryName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get repositories p2 proxy by repositoryname params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRepositoriesP2ProxyByRepositorynameParams) WithDefaults() *GetRepositoriesP2ProxyByRepositorynameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get repositories p2 proxy by repositoryname params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRepositoriesP2ProxyByRepositorynameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get repositories p2 proxy by repositoryname params
func (o *GetRepositoriesP2ProxyByRepositorynameParams) WithTimeout(timeout time.Duration) *GetRepositoriesP2ProxyByRepositorynameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repositories p2 proxy by repositoryname params
func (o *GetRepositoriesP2ProxyByRepositorynameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repositories p2 proxy by repositoryname params
func (o *GetRepositoriesP2ProxyByRepositorynameParams) WithContext(ctx context.Context) *GetRepositoriesP2ProxyByRepositorynameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repositories p2 proxy by repositoryname params
func (o *GetRepositoriesP2ProxyByRepositorynameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repositories p2 proxy by repositoryname params
func (o *GetRepositoriesP2ProxyByRepositorynameParams) WithHTTPClient(client *http.Client) *GetRepositoriesP2ProxyByRepositorynameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repositories p2 proxy by repositoryname params
func (o *GetRepositoriesP2ProxyByRepositorynameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepositoryName adds the repositoryName to the get repositories p2 proxy by repositoryname params
func (o *GetRepositoriesP2ProxyByRepositorynameParams) WithRepositoryName(repositoryName string) *GetRepositoriesP2ProxyByRepositorynameParams {
	o.SetRepositoryName(repositoryName)
	return o
}

// SetRepositoryName adds the repositoryName to the get repositories p2 proxy by repositoryname params
func (o *GetRepositoriesP2ProxyByRepositorynameParams) SetRepositoryName(repositoryName string) {
	o.RepositoryName = repositoryName
}

// WriteToRequest writes these params to a swagger request
func (o *GetRepositoriesP2ProxyByRepositorynameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repositoryName
	if err := r.SetPathParam("repositoryName", o.RepositoryName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
