// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRepositoriesHelmProxyByRepositoryNameParams creates a new GetRepositoriesHelmProxyByRepositoryNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRepositoriesHelmProxyByRepositoryNameParams() *GetRepositoriesHelmProxyByRepositoryNameParams {
	return &GetRepositoriesHelmProxyByRepositoryNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRepositoriesHelmProxyByRepositoryNameParamsWithTimeout creates a new GetRepositoriesHelmProxyByRepositoryNameParams object
// with the ability to set a timeout on a request.
func NewGetRepositoriesHelmProxyByRepositoryNameParamsWithTimeout(timeout time.Duration) *GetRepositoriesHelmProxyByRepositoryNameParams {
	return &GetRepositoriesHelmProxyByRepositoryNameParams{
		timeout: timeout,
	}
}

// NewGetRepositoriesHelmProxyByRepositoryNameParamsWithContext creates a new GetRepositoriesHelmProxyByRepositoryNameParams object
// with the ability to set a context for a request.
func NewGetRepositoriesHelmProxyByRepositoryNameParamsWithContext(ctx context.Context) *GetRepositoriesHelmProxyByRepositoryNameParams {
	return &GetRepositoriesHelmProxyByRepositoryNameParams{
		Context: ctx,
	}
}

// NewGetRepositoriesHelmProxyByRepositoryNameParamsWithHTTPClient creates a new GetRepositoriesHelmProxyByRepositoryNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRepositoriesHelmProxyByRepositoryNameParamsWithHTTPClient(client *http.Client) *GetRepositoriesHelmProxyByRepositoryNameParams {
	return &GetRepositoriesHelmProxyByRepositoryNameParams{
		HTTPClient: client,
	}
}

/*
GetRepositoriesHelmProxyByRepositoryNameParams contains all the parameters to send to the API endpoint

	for the get repositories helm proxy by repository name operation.

	Typically these are written to a http.Request.
*/
type GetRepositoriesHelmProxyByRepositoryNameParams struct {

	// RepositoryName.
	RepositoryName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get repositories helm proxy by repository name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRepositoriesHelmProxyByRepositoryNameParams) WithDefaults() *GetRepositoriesHelmProxyByRepositoryNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get repositories helm proxy by repository name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRepositoriesHelmProxyByRepositoryNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get repositories helm proxy by repository name params
func (o *GetRepositoriesHelmProxyByRepositoryNameParams) WithTimeout(timeout time.Duration) *GetRepositoriesHelmProxyByRepositoryNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repositories helm proxy by repository name params
func (o *GetRepositoriesHelmProxyByRepositoryNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repositories helm proxy by repository name params
func (o *GetRepositoriesHelmProxyByRepositoryNameParams) WithContext(ctx context.Context) *GetRepositoriesHelmProxyByRepositoryNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repositories helm proxy by repository name params
func (o *GetRepositoriesHelmProxyByRepositoryNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repositories helm proxy by repository name params
func (o *GetRepositoriesHelmProxyByRepositoryNameParams) WithHTTPClient(client *http.Client) *GetRepositoriesHelmProxyByRepositoryNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repositories helm proxy by repository name params
func (o *GetRepositoriesHelmProxyByRepositoryNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepositoryName adds the repositoryName to the get repositories helm proxy by repository name params
func (o *GetRepositoriesHelmProxyByRepositoryNameParams) WithRepositoryName(repositoryName string) *GetRepositoriesHelmProxyByRepositoryNameParams {
	o.SetRepositoryName(repositoryName)
	return o
}

// SetRepositoryName adds the repositoryName to the get repositories helm proxy by repository name params
func (o *GetRepositoriesHelmProxyByRepositoryNameParams) SetRepositoryName(repositoryName string) {
	o.RepositoryName = repositoryName
}

// WriteToRequest writes these params to a swagger request
func (o *GetRepositoriesHelmProxyByRepositoryNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repositoryName
	if err := r.SetPathParam("repositoryName", o.RepositoryName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
