// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dmji/go-nexus/models"
)

// GetRepositoriesMavenGroupByRepositoryNameReader is a Reader for the GetRepositoriesMavenGroupByRepositoryName structure.
type GetRepositoriesMavenGroupByRepositoryNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRepositoriesMavenGroupByRepositoryNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRepositoriesMavenGroupByRepositoryNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/repositories/maven/group/{repositoryName}] GetRepositoriesMavenGroupByRepositoryName", response, response.Code())
	}
}

// NewGetRepositoriesMavenGroupByRepositoryNameOK creates a GetRepositoriesMavenGroupByRepositoryNameOK with default headers values
func NewGetRepositoriesMavenGroupByRepositoryNameOK() *GetRepositoriesMavenGroupByRepositoryNameOK {
	return &GetRepositoriesMavenGroupByRepositoryNameOK{}
}

/*
GetRepositoriesMavenGroupByRepositoryNameOK describes a response with status code 200, with default header values.

successful operation
*/
type GetRepositoriesMavenGroupByRepositoryNameOK struct {
	Payload *models.SimpleAPIGroupRepository
}

// IsSuccess returns true when this get repositories maven group by repository name o k response has a 2xx status code
func (o *GetRepositoriesMavenGroupByRepositoryNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get repositories maven group by repository name o k response has a 3xx status code
func (o *GetRepositoriesMavenGroupByRepositoryNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get repositories maven group by repository name o k response has a 4xx status code
func (o *GetRepositoriesMavenGroupByRepositoryNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get repositories maven group by repository name o k response has a 5xx status code
func (o *GetRepositoriesMavenGroupByRepositoryNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get repositories maven group by repository name o k response a status code equal to that given
func (o *GetRepositoriesMavenGroupByRepositoryNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get repositories maven group by repository name o k response
func (o *GetRepositoriesMavenGroupByRepositoryNameOK) Code() int {
	return 200
}

func (o *GetRepositoriesMavenGroupByRepositoryNameOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/repositories/maven/group/{repositoryName}][%d] getRepositoriesMavenGroupByRepositoryNameOK %s", 200, payload)
}

func (o *GetRepositoriesMavenGroupByRepositoryNameOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/repositories/maven/group/{repositoryName}][%d] getRepositoriesMavenGroupByRepositoryNameOK %s", 200, payload)
}

func (o *GetRepositoriesMavenGroupByRepositoryNameOK) GetPayload() *models.SimpleAPIGroupRepository {
	return o.Payload
}

func (o *GetRepositoriesMavenGroupByRepositoryNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimpleAPIGroupRepository)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
