// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRepositoriesCargoProxyByRepositorynameParams creates a new GetRepositoriesCargoProxyByRepositorynameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRepositoriesCargoProxyByRepositorynameParams() *GetRepositoriesCargoProxyByRepositorynameParams {
	return &GetRepositoriesCargoProxyByRepositorynameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRepositoriesCargoProxyByRepositorynameParamsWithTimeout creates a new GetRepositoriesCargoProxyByRepositorynameParams object
// with the ability to set a timeout on a request.
func NewGetRepositoriesCargoProxyByRepositorynameParamsWithTimeout(timeout time.Duration) *GetRepositoriesCargoProxyByRepositorynameParams {
	return &GetRepositoriesCargoProxyByRepositorynameParams{
		timeout: timeout,
	}
}

// NewGetRepositoriesCargoProxyByRepositorynameParamsWithContext creates a new GetRepositoriesCargoProxyByRepositorynameParams object
// with the ability to set a context for a request.
func NewGetRepositoriesCargoProxyByRepositorynameParamsWithContext(ctx context.Context) *GetRepositoriesCargoProxyByRepositorynameParams {
	return &GetRepositoriesCargoProxyByRepositorynameParams{
		Context: ctx,
	}
}

// NewGetRepositoriesCargoProxyByRepositorynameParamsWithHTTPClient creates a new GetRepositoriesCargoProxyByRepositorynameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRepositoriesCargoProxyByRepositorynameParamsWithHTTPClient(client *http.Client) *GetRepositoriesCargoProxyByRepositorynameParams {
	return &GetRepositoriesCargoProxyByRepositorynameParams{
		HTTPClient: client,
	}
}

/*
GetRepositoriesCargoProxyByRepositorynameParams contains all the parameters to send to the API endpoint

	for the get repositories cargo proxy by repositoryname operation.

	Typically these are written to a http.Request.
*/
type GetRepositoriesCargoProxyByRepositorynameParams struct {

	// RepositoryName.
	RepositoryName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get repositories cargo proxy by repositoryname params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRepositoriesCargoProxyByRepositorynameParams) WithDefaults() *GetRepositoriesCargoProxyByRepositorynameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get repositories cargo proxy by repositoryname params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRepositoriesCargoProxyByRepositorynameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get repositories cargo proxy by repositoryname params
func (o *GetRepositoriesCargoProxyByRepositorynameParams) WithTimeout(timeout time.Duration) *GetRepositoriesCargoProxyByRepositorynameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repositories cargo proxy by repositoryname params
func (o *GetRepositoriesCargoProxyByRepositorynameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repositories cargo proxy by repositoryname params
func (o *GetRepositoriesCargoProxyByRepositorynameParams) WithContext(ctx context.Context) *GetRepositoriesCargoProxyByRepositorynameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repositories cargo proxy by repositoryname params
func (o *GetRepositoriesCargoProxyByRepositorynameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repositories cargo proxy by repositoryname params
func (o *GetRepositoriesCargoProxyByRepositorynameParams) WithHTTPClient(client *http.Client) *GetRepositoriesCargoProxyByRepositorynameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repositories cargo proxy by repositoryname params
func (o *GetRepositoriesCargoProxyByRepositorynameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepositoryName adds the repositoryName to the get repositories cargo proxy by repositoryname params
func (o *GetRepositoriesCargoProxyByRepositorynameParams) WithRepositoryName(repositoryName string) *GetRepositoriesCargoProxyByRepositorynameParams {
	o.SetRepositoryName(repositoryName)
	return o
}

// SetRepositoryName adds the repositoryName to the get repositories cargo proxy by repositoryname params
func (o *GetRepositoriesCargoProxyByRepositorynameParams) SetRepositoryName(repositoryName string) {
	o.RepositoryName = repositoryName
}

// WriteToRequest writes these params to a swagger request
func (o *GetRepositoriesCargoProxyByRepositorynameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repositoryName
	if err := r.SetPathParam("repositoryName", o.RepositoryName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
