// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dmji/go-nexus/models"
)

// GetRepository29Reader is a Reader for the GetRepository29 structure.
type GetRepository29Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRepository29Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRepository29OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/repositories/npm/proxy/{repositoryName}] getRepository_29", response, response.Code())
	}
}

// NewGetRepository29OK creates a GetRepository29OK with default headers values
func NewGetRepository29OK() *GetRepository29OK {
	return &GetRepository29OK{}
}

/*
GetRepository29OK describes a response with status code 200, with default header values.

successful operation
*/
type GetRepository29OK struct {
	Payload *models.NpmProxyAPIRepository
}

// IsSuccess returns true when this get repository29 o k response has a 2xx status code
func (o *GetRepository29OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get repository29 o k response has a 3xx status code
func (o *GetRepository29OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get repository29 o k response has a 4xx status code
func (o *GetRepository29OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get repository29 o k response has a 5xx status code
func (o *GetRepository29OK) IsServerError() bool {
	return false
}

// IsCode returns true when this get repository29 o k response a status code equal to that given
func (o *GetRepository29OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get repository29 o k response
func (o *GetRepository29OK) Code() int {
	return 200
}

func (o *GetRepository29OK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/repositories/npm/proxy/{repositoryName}][%d] getRepository29OK %s", 200, payload)
}

func (o *GetRepository29OK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/repositories/npm/proxy/{repositoryName}][%d] getRepository29OK %s", 200, payload)
}

func (o *GetRepository29OK) GetPayload() *models.NpmProxyAPIRepository {
	return o.Payload
}

func (o *GetRepository29OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NpmProxyAPIRepository)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
