// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/dmji/go-nexus/models"
)

// NewPostRepositoriesComposerProxyParams creates a new PostRepositoriesComposerProxyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostRepositoriesComposerProxyParams() *PostRepositoriesComposerProxyParams {
	return &PostRepositoriesComposerProxyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostRepositoriesComposerProxyParamsWithTimeout creates a new PostRepositoriesComposerProxyParams object
// with the ability to set a timeout on a request.
func NewPostRepositoriesComposerProxyParamsWithTimeout(timeout time.Duration) *PostRepositoriesComposerProxyParams {
	return &PostRepositoriesComposerProxyParams{
		timeout: timeout,
	}
}

// NewPostRepositoriesComposerProxyParamsWithContext creates a new PostRepositoriesComposerProxyParams object
// with the ability to set a context for a request.
func NewPostRepositoriesComposerProxyParamsWithContext(ctx context.Context) *PostRepositoriesComposerProxyParams {
	return &PostRepositoriesComposerProxyParams{
		Context: ctx,
	}
}

// NewPostRepositoriesComposerProxyParamsWithHTTPClient creates a new PostRepositoriesComposerProxyParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostRepositoriesComposerProxyParamsWithHTTPClient(client *http.Client) *PostRepositoriesComposerProxyParams {
	return &PostRepositoriesComposerProxyParams{
		HTTPClient: client,
	}
}

/*
PostRepositoriesComposerProxyParams contains all the parameters to send to the API endpoint

	for the post repositories composer proxy operation.

	Typically these are written to a http.Request.
*/
type PostRepositoriesComposerProxyParams struct {

	// Body.
	Body *models.ComposerProxyRepositoryAPIRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post repositories composer proxy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRepositoriesComposerProxyParams) WithDefaults() *PostRepositoriesComposerProxyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post repositories composer proxy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRepositoriesComposerProxyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post repositories composer proxy params
func (o *PostRepositoriesComposerProxyParams) WithTimeout(timeout time.Duration) *PostRepositoriesComposerProxyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post repositories composer proxy params
func (o *PostRepositoriesComposerProxyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post repositories composer proxy params
func (o *PostRepositoriesComposerProxyParams) WithContext(ctx context.Context) *PostRepositoriesComposerProxyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post repositories composer proxy params
func (o *PostRepositoriesComposerProxyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post repositories composer proxy params
func (o *PostRepositoriesComposerProxyParams) WithHTTPClient(client *http.Client) *PostRepositoriesComposerProxyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post repositories composer proxy params
func (o *PostRepositoriesComposerProxyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post repositories composer proxy params
func (o *PostRepositoriesComposerProxyParams) WithBody(body *models.ComposerProxyRepositoryAPIRequest) *PostRepositoriesComposerProxyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post repositories composer proxy params
func (o *PostRepositoriesComposerProxyParams) SetBody(body *models.ComposerProxyRepositoryAPIRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostRepositoriesComposerProxyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
