// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/dmji/go-nexus/models"
)

// NewPostRepositoriesAptHostedParams creates a new PostRepositoriesAptHostedParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostRepositoriesAptHostedParams() *PostRepositoriesAptHostedParams {
	return &PostRepositoriesAptHostedParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostRepositoriesAptHostedParamsWithTimeout creates a new PostRepositoriesAptHostedParams object
// with the ability to set a timeout on a request.
func NewPostRepositoriesAptHostedParamsWithTimeout(timeout time.Duration) *PostRepositoriesAptHostedParams {
	return &PostRepositoriesAptHostedParams{
		timeout: timeout,
	}
}

// NewPostRepositoriesAptHostedParamsWithContext creates a new PostRepositoriesAptHostedParams object
// with the ability to set a context for a request.
func NewPostRepositoriesAptHostedParamsWithContext(ctx context.Context) *PostRepositoriesAptHostedParams {
	return &PostRepositoriesAptHostedParams{
		Context: ctx,
	}
}

// NewPostRepositoriesAptHostedParamsWithHTTPClient creates a new PostRepositoriesAptHostedParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostRepositoriesAptHostedParamsWithHTTPClient(client *http.Client) *PostRepositoriesAptHostedParams {
	return &PostRepositoriesAptHostedParams{
		HTTPClient: client,
	}
}

/*
PostRepositoriesAptHostedParams contains all the parameters to send to the API endpoint

	for the post repositories apt hosted operation.

	Typically these are written to a http.Request.
*/
type PostRepositoriesAptHostedParams struct {

	// Body.
	Body *models.AptHostedRepositoryAPIRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post repositories apt hosted params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRepositoriesAptHostedParams) WithDefaults() *PostRepositoriesAptHostedParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post repositories apt hosted params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRepositoriesAptHostedParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post repositories apt hosted params
func (o *PostRepositoriesAptHostedParams) WithTimeout(timeout time.Duration) *PostRepositoriesAptHostedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post repositories apt hosted params
func (o *PostRepositoriesAptHostedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post repositories apt hosted params
func (o *PostRepositoriesAptHostedParams) WithContext(ctx context.Context) *PostRepositoriesAptHostedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post repositories apt hosted params
func (o *PostRepositoriesAptHostedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post repositories apt hosted params
func (o *PostRepositoriesAptHostedParams) WithHTTPClient(client *http.Client) *PostRepositoriesAptHostedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post repositories apt hosted params
func (o *PostRepositoriesAptHostedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post repositories apt hosted params
func (o *PostRepositoriesAptHostedParams) WithBody(body *models.AptHostedRepositoryAPIRequest) *PostRepositoriesAptHostedParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post repositories apt hosted params
func (o *PostRepositoriesAptHostedParams) SetBody(body *models.AptHostedRepositoryAPIRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostRepositoriesAptHostedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
