// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/dmji/go-nexus/models"
)

// NewPostRepositoriesCargoHostedParams creates a new PostRepositoriesCargoHostedParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostRepositoriesCargoHostedParams() *PostRepositoriesCargoHostedParams {
	return &PostRepositoriesCargoHostedParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostRepositoriesCargoHostedParamsWithTimeout creates a new PostRepositoriesCargoHostedParams object
// with the ability to set a timeout on a request.
func NewPostRepositoriesCargoHostedParamsWithTimeout(timeout time.Duration) *PostRepositoriesCargoHostedParams {
	return &PostRepositoriesCargoHostedParams{
		timeout: timeout,
	}
}

// NewPostRepositoriesCargoHostedParamsWithContext creates a new PostRepositoriesCargoHostedParams object
// with the ability to set a context for a request.
func NewPostRepositoriesCargoHostedParamsWithContext(ctx context.Context) *PostRepositoriesCargoHostedParams {
	return &PostRepositoriesCargoHostedParams{
		Context: ctx,
	}
}

// NewPostRepositoriesCargoHostedParamsWithHTTPClient creates a new PostRepositoriesCargoHostedParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostRepositoriesCargoHostedParamsWithHTTPClient(client *http.Client) *PostRepositoriesCargoHostedParams {
	return &PostRepositoriesCargoHostedParams{
		HTTPClient: client,
	}
}

/*
PostRepositoriesCargoHostedParams contains all the parameters to send to the API endpoint

	for the post repositories cargo hosted operation.

	Typically these are written to a http.Request.
*/
type PostRepositoriesCargoHostedParams struct {

	// Body.
	Body *models.CargoHostedRepositoryAPIRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post repositories cargo hosted params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRepositoriesCargoHostedParams) WithDefaults() *PostRepositoriesCargoHostedParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post repositories cargo hosted params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRepositoriesCargoHostedParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post repositories cargo hosted params
func (o *PostRepositoriesCargoHostedParams) WithTimeout(timeout time.Duration) *PostRepositoriesCargoHostedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post repositories cargo hosted params
func (o *PostRepositoriesCargoHostedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post repositories cargo hosted params
func (o *PostRepositoriesCargoHostedParams) WithContext(ctx context.Context) *PostRepositoriesCargoHostedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post repositories cargo hosted params
func (o *PostRepositoriesCargoHostedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post repositories cargo hosted params
func (o *PostRepositoriesCargoHostedParams) WithHTTPClient(client *http.Client) *PostRepositoriesCargoHostedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post repositories cargo hosted params
func (o *PostRepositoriesCargoHostedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post repositories cargo hosted params
func (o *PostRepositoriesCargoHostedParams) WithBody(body *models.CargoHostedRepositoryAPIRequest) *PostRepositoriesCargoHostedParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post repositories cargo hosted params
func (o *PostRepositoriesCargoHostedParams) SetBody(body *models.CargoHostedRepositoryAPIRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostRepositoriesCargoHostedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
