// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/dmji/go-nexus/models"
)

// NewPutRepositoriesMavenHostedByRepositorynameParams creates a new PutRepositoriesMavenHostedByRepositorynameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutRepositoriesMavenHostedByRepositorynameParams() *PutRepositoriesMavenHostedByRepositorynameParams {
	return &PutRepositoriesMavenHostedByRepositorynameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutRepositoriesMavenHostedByRepositorynameParamsWithTimeout creates a new PutRepositoriesMavenHostedByRepositorynameParams object
// with the ability to set a timeout on a request.
func NewPutRepositoriesMavenHostedByRepositorynameParamsWithTimeout(timeout time.Duration) *PutRepositoriesMavenHostedByRepositorynameParams {
	return &PutRepositoriesMavenHostedByRepositorynameParams{
		timeout: timeout,
	}
}

// NewPutRepositoriesMavenHostedByRepositorynameParamsWithContext creates a new PutRepositoriesMavenHostedByRepositorynameParams object
// with the ability to set a context for a request.
func NewPutRepositoriesMavenHostedByRepositorynameParamsWithContext(ctx context.Context) *PutRepositoriesMavenHostedByRepositorynameParams {
	return &PutRepositoriesMavenHostedByRepositorynameParams{
		Context: ctx,
	}
}

// NewPutRepositoriesMavenHostedByRepositorynameParamsWithHTTPClient creates a new PutRepositoriesMavenHostedByRepositorynameParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutRepositoriesMavenHostedByRepositorynameParamsWithHTTPClient(client *http.Client) *PutRepositoriesMavenHostedByRepositorynameParams {
	return &PutRepositoriesMavenHostedByRepositorynameParams{
		HTTPClient: client,
	}
}

/*
PutRepositoriesMavenHostedByRepositorynameParams contains all the parameters to send to the API endpoint

	for the put repositories maven hosted by repositoryname operation.

	Typically these are written to a http.Request.
*/
type PutRepositoriesMavenHostedByRepositorynameParams struct {

	// Body.
	Body *models.MavenHostedRepositoryAPIRequest

	/* RepositoryName.

	   Name of the repository to update
	*/
	RepositoryName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put repositories maven hosted by repositoryname params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutRepositoriesMavenHostedByRepositorynameParams) WithDefaults() *PutRepositoriesMavenHostedByRepositorynameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put repositories maven hosted by repositoryname params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutRepositoriesMavenHostedByRepositorynameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put repositories maven hosted by repositoryname params
func (o *PutRepositoriesMavenHostedByRepositorynameParams) WithTimeout(timeout time.Duration) *PutRepositoriesMavenHostedByRepositorynameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put repositories maven hosted by repositoryname params
func (o *PutRepositoriesMavenHostedByRepositorynameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put repositories maven hosted by repositoryname params
func (o *PutRepositoriesMavenHostedByRepositorynameParams) WithContext(ctx context.Context) *PutRepositoriesMavenHostedByRepositorynameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put repositories maven hosted by repositoryname params
func (o *PutRepositoriesMavenHostedByRepositorynameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put repositories maven hosted by repositoryname params
func (o *PutRepositoriesMavenHostedByRepositorynameParams) WithHTTPClient(client *http.Client) *PutRepositoriesMavenHostedByRepositorynameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put repositories maven hosted by repositoryname params
func (o *PutRepositoriesMavenHostedByRepositorynameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put repositories maven hosted by repositoryname params
func (o *PutRepositoriesMavenHostedByRepositorynameParams) WithBody(body *models.MavenHostedRepositoryAPIRequest) *PutRepositoriesMavenHostedByRepositorynameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put repositories maven hosted by repositoryname params
func (o *PutRepositoriesMavenHostedByRepositorynameParams) SetBody(body *models.MavenHostedRepositoryAPIRequest) {
	o.Body = body
}

// WithRepositoryName adds the repositoryName to the put repositories maven hosted by repositoryname params
func (o *PutRepositoriesMavenHostedByRepositorynameParams) WithRepositoryName(repositoryName string) *PutRepositoriesMavenHostedByRepositorynameParams {
	o.SetRepositoryName(repositoryName)
	return o
}

// SetRepositoryName adds the repositoryName to the put repositories maven hosted by repositoryname params
func (o *PutRepositoriesMavenHostedByRepositorynameParams) SetRepositoryName(repositoryName string) {
	o.RepositoryName = repositoryName
}

// WriteToRequest writes these params to a swagger request
func (o *PutRepositoriesMavenHostedByRepositorynameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param repositoryName
	if err := r.SetPathParam("repositoryName", o.RepositoryName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
