// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/dmji/go-nexus/models"
)

// NewPutRepositoriesHelmProxyByRepositoryNameParams creates a new PutRepositoriesHelmProxyByRepositoryNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutRepositoriesHelmProxyByRepositoryNameParams() *PutRepositoriesHelmProxyByRepositoryNameParams {
	return &PutRepositoriesHelmProxyByRepositoryNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutRepositoriesHelmProxyByRepositoryNameParamsWithTimeout creates a new PutRepositoriesHelmProxyByRepositoryNameParams object
// with the ability to set a timeout on a request.
func NewPutRepositoriesHelmProxyByRepositoryNameParamsWithTimeout(timeout time.Duration) *PutRepositoriesHelmProxyByRepositoryNameParams {
	return &PutRepositoriesHelmProxyByRepositoryNameParams{
		timeout: timeout,
	}
}

// NewPutRepositoriesHelmProxyByRepositoryNameParamsWithContext creates a new PutRepositoriesHelmProxyByRepositoryNameParams object
// with the ability to set a context for a request.
func NewPutRepositoriesHelmProxyByRepositoryNameParamsWithContext(ctx context.Context) *PutRepositoriesHelmProxyByRepositoryNameParams {
	return &PutRepositoriesHelmProxyByRepositoryNameParams{
		Context: ctx,
	}
}

// NewPutRepositoriesHelmProxyByRepositoryNameParamsWithHTTPClient creates a new PutRepositoriesHelmProxyByRepositoryNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutRepositoriesHelmProxyByRepositoryNameParamsWithHTTPClient(client *http.Client) *PutRepositoriesHelmProxyByRepositoryNameParams {
	return &PutRepositoriesHelmProxyByRepositoryNameParams{
		HTTPClient: client,
	}
}

/*
PutRepositoriesHelmProxyByRepositoryNameParams contains all the parameters to send to the API endpoint

	for the put repositories helm proxy by repository name operation.

	Typically these are written to a http.Request.
*/
type PutRepositoriesHelmProxyByRepositoryNameParams struct {

	// Body.
	Body *models.HelmProxyRepositoryAPIRequest

	/* RepositoryName.

	   Name of the repository to update
	*/
	RepositoryName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put repositories helm proxy by repository name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutRepositoriesHelmProxyByRepositoryNameParams) WithDefaults() *PutRepositoriesHelmProxyByRepositoryNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put repositories helm proxy by repository name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutRepositoriesHelmProxyByRepositoryNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put repositories helm proxy by repository name params
func (o *PutRepositoriesHelmProxyByRepositoryNameParams) WithTimeout(timeout time.Duration) *PutRepositoriesHelmProxyByRepositoryNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put repositories helm proxy by repository name params
func (o *PutRepositoriesHelmProxyByRepositoryNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put repositories helm proxy by repository name params
func (o *PutRepositoriesHelmProxyByRepositoryNameParams) WithContext(ctx context.Context) *PutRepositoriesHelmProxyByRepositoryNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put repositories helm proxy by repository name params
func (o *PutRepositoriesHelmProxyByRepositoryNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put repositories helm proxy by repository name params
func (o *PutRepositoriesHelmProxyByRepositoryNameParams) WithHTTPClient(client *http.Client) *PutRepositoriesHelmProxyByRepositoryNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put repositories helm proxy by repository name params
func (o *PutRepositoriesHelmProxyByRepositoryNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put repositories helm proxy by repository name params
func (o *PutRepositoriesHelmProxyByRepositoryNameParams) WithBody(body *models.HelmProxyRepositoryAPIRequest) *PutRepositoriesHelmProxyByRepositoryNameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put repositories helm proxy by repository name params
func (o *PutRepositoriesHelmProxyByRepositoryNameParams) SetBody(body *models.HelmProxyRepositoryAPIRequest) {
	o.Body = body
}

// WithRepositoryName adds the repositoryName to the put repositories helm proxy by repository name params
func (o *PutRepositoriesHelmProxyByRepositoryNameParams) WithRepositoryName(repositoryName string) *PutRepositoriesHelmProxyByRepositoryNameParams {
	o.SetRepositoryName(repositoryName)
	return o
}

// SetRepositoryName adds the repositoryName to the put repositories helm proxy by repository name params
func (o *PutRepositoriesHelmProxyByRepositoryNameParams) SetRepositoryName(repositoryName string) {
	o.RepositoryName = repositoryName
}

// WriteToRequest writes these params to a swagger request
func (o *PutRepositoriesHelmProxyByRepositoryNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param repositoryName
	if err := r.SetPathParam("repositoryName", o.RepositoryName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
