// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostEmailVerifyParams creates a new PostEmailVerifyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostEmailVerifyParams() *PostEmailVerifyParams {
	return &PostEmailVerifyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostEmailVerifyParamsWithTimeout creates a new PostEmailVerifyParams object
// with the ability to set a timeout on a request.
func NewPostEmailVerifyParamsWithTimeout(timeout time.Duration) *PostEmailVerifyParams {
	return &PostEmailVerifyParams{
		timeout: timeout,
	}
}

// NewPostEmailVerifyParamsWithContext creates a new PostEmailVerifyParams object
// with the ability to set a context for a request.
func NewPostEmailVerifyParamsWithContext(ctx context.Context) *PostEmailVerifyParams {
	return &PostEmailVerifyParams{
		Context: ctx,
	}
}

// NewPostEmailVerifyParamsWithHTTPClient creates a new PostEmailVerifyParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostEmailVerifyParamsWithHTTPClient(client *http.Client) *PostEmailVerifyParams {
	return &PostEmailVerifyParams{
		HTTPClient: client,
	}
}

/*
PostEmailVerifyParams contains all the parameters to send to the API endpoint

	for the post email verify operation.

	Typically these are written to a http.Request.
*/
type PostEmailVerifyParams struct {

	/* Body.

	   An email address to send a test email to
	*/
	Body string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post email verify params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostEmailVerifyParams) WithDefaults() *PostEmailVerifyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post email verify params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostEmailVerifyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post email verify params
func (o *PostEmailVerifyParams) WithTimeout(timeout time.Duration) *PostEmailVerifyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post email verify params
func (o *PostEmailVerifyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post email verify params
func (o *PostEmailVerifyParams) WithContext(ctx context.Context) *PostEmailVerifyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post email verify params
func (o *PostEmailVerifyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post email verify params
func (o *PostEmailVerifyParams) WithHTTPClient(client *http.Client) *PostEmailVerifyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post email verify params
func (o *PostEmailVerifyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post email verify params
func (o *PostEmailVerifyParams) WithBody(body string) *PostEmailVerifyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post email verify params
func (o *PostEmailVerifyParams) SetBody(body string) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostEmailVerifyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
