// Code generated by go-swagger; DO NOT EDIT.

package security_management_realms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSecurityRealmsAvailableParams creates a new GetSecurityRealmsAvailableParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSecurityRealmsAvailableParams() *GetSecurityRealmsAvailableParams {
	return &GetSecurityRealmsAvailableParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSecurityRealmsAvailableParamsWithTimeout creates a new GetSecurityRealmsAvailableParams object
// with the ability to set a timeout on a request.
func NewGetSecurityRealmsAvailableParamsWithTimeout(timeout time.Duration) *GetSecurityRealmsAvailableParams {
	return &GetSecurityRealmsAvailableParams{
		timeout: timeout,
	}
}

// NewGetSecurityRealmsAvailableParamsWithContext creates a new GetSecurityRealmsAvailableParams object
// with the ability to set a context for a request.
func NewGetSecurityRealmsAvailableParamsWithContext(ctx context.Context) *GetSecurityRealmsAvailableParams {
	return &GetSecurityRealmsAvailableParams{
		Context: ctx,
	}
}

// NewGetSecurityRealmsAvailableParamsWithHTTPClient creates a new GetSecurityRealmsAvailableParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSecurityRealmsAvailableParamsWithHTTPClient(client *http.Client) *GetSecurityRealmsAvailableParams {
	return &GetSecurityRealmsAvailableParams{
		HTTPClient: client,
	}
}

/*
GetSecurityRealmsAvailableParams contains all the parameters to send to the API endpoint

	for the get security realms available operation.

	Typically these are written to a http.Request.
*/
type GetSecurityRealmsAvailableParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get security realms available params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSecurityRealmsAvailableParams) WithDefaults() *GetSecurityRealmsAvailableParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get security realms available params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSecurityRealmsAvailableParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get security realms available params
func (o *GetSecurityRealmsAvailableParams) WithTimeout(timeout time.Duration) *GetSecurityRealmsAvailableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get security realms available params
func (o *GetSecurityRealmsAvailableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get security realms available params
func (o *GetSecurityRealmsAvailableParams) WithContext(ctx context.Context) *GetSecurityRealmsAvailableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get security realms available params
func (o *GetSecurityRealmsAvailableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get security realms available params
func (o *GetSecurityRealmsAvailableParams) WithHTTPClient(client *http.Client) *GetSecurityRealmsAvailableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get security realms available params
func (o *GetSecurityRealmsAvailableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSecurityRealmsAvailableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
