// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAssetsByIDParams creates a new DeleteAssetsByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAssetsByIDParams() *DeleteAssetsByIDParams {
	return &DeleteAssetsByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAssetsByIDParamsWithTimeout creates a new DeleteAssetsByIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAssetsByIDParamsWithTimeout(timeout time.Duration) *DeleteAssetsByIDParams {
	return &DeleteAssetsByIDParams{
		timeout: timeout,
	}
}

// NewDeleteAssetsByIDParamsWithContext creates a new DeleteAssetsByIDParams object
// with the ability to set a context for a request.
func NewDeleteAssetsByIDParamsWithContext(ctx context.Context) *DeleteAssetsByIDParams {
	return &DeleteAssetsByIDParams{
		Context: ctx,
	}
}

// NewDeleteAssetsByIDParamsWithHTTPClient creates a new DeleteAssetsByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAssetsByIDParamsWithHTTPClient(client *http.Client) *DeleteAssetsByIDParams {
	return &DeleteAssetsByIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAssetsByIDParams contains all the parameters to send to the API endpoint

	for the delete assets by Id operation.

	Typically these are written to a http.Request.
*/
type DeleteAssetsByIDParams struct {

	/* ID.

	   Id of the asset to delete
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete assets by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAssetsByIDParams) WithDefaults() *DeleteAssetsByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete assets by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAssetsByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete assets by Id params
func (o *DeleteAssetsByIDParams) WithTimeout(timeout time.Duration) *DeleteAssetsByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete assets by Id params
func (o *DeleteAssetsByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete assets by Id params
func (o *DeleteAssetsByIDParams) WithContext(ctx context.Context) *DeleteAssetsByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete assets by Id params
func (o *DeleteAssetsByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete assets by Id params
func (o *DeleteAssetsByIDParams) WithHTTPClient(client *http.Client) *DeleteAssetsByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete assets by Id params
func (o *DeleteAssetsByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete assets by Id params
func (o *DeleteAssetsByIDParams) WithID(id string) *DeleteAssetsByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete assets by Id params
func (o *DeleteAssetsByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAssetsByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
