// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GroupBlobStoreAPICreateRequest group blob store Api create request
//
// swagger:model GroupBlobStoreApiCreateRequest
type GroupBlobStoreAPICreateRequest struct {

	// fill policy
	// Enum: ["roundRobin","writeToFirst"]
	FillPolicy string `json:"fillPolicy,omitempty"`

	// List of the names of blob stores that are members of this group
	Members []string `json:"members"`

	// name
	Name string `json:"name,omitempty"`

	// Settings to control the soft quota
	SoftQuota *BlobStoreAPISoftQuota `json:"softQuota,omitempty"`
}

// Validate validates this group blob store Api create request
func (m *GroupBlobStoreAPICreateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFillPolicy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSoftQuota(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var groupBlobStoreApiCreateRequestTypeFillPolicyPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["roundRobin","writeToFirst"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		groupBlobStoreApiCreateRequestTypeFillPolicyPropEnum = append(groupBlobStoreApiCreateRequestTypeFillPolicyPropEnum, v)
	}
}

const (

	// GroupBlobStoreAPICreateRequestFillPolicyRoundRobin captures enum value "roundRobin"
	GroupBlobStoreAPICreateRequestFillPolicyRoundRobin string = "roundRobin"

	// GroupBlobStoreAPICreateRequestFillPolicyWriteToFirst captures enum value "writeToFirst"
	GroupBlobStoreAPICreateRequestFillPolicyWriteToFirst string = "writeToFirst"
)

// prop value enum
func (m *GroupBlobStoreAPICreateRequest) validateFillPolicyEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, groupBlobStoreApiCreateRequestTypeFillPolicyPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GroupBlobStoreAPICreateRequest) validateFillPolicy(formats strfmt.Registry) error {
	if swag.IsZero(m.FillPolicy) { // not required
		return nil
	}

	// value enum
	if err := m.validateFillPolicyEnum("fillPolicy", "body", m.FillPolicy); err != nil {
		return err
	}

	return nil
}

func (m *GroupBlobStoreAPICreateRequest) validateSoftQuota(formats strfmt.Registry) error {
	if swag.IsZero(m.SoftQuota) { // not required
		return nil
	}

	if m.SoftQuota != nil {
		if err := m.SoftQuota.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("softQuota")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("softQuota")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this group blob store Api create request based on the context it is used
func (m *GroupBlobStoreAPICreateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSoftQuota(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GroupBlobStoreAPICreateRequest) contextValidateSoftQuota(ctx context.Context, formats strfmt.Registry) error {

	if m.SoftQuota != nil {

		if swag.IsZero(m.SoftQuota) { // not required
			return nil
		}

		if err := m.SoftQuota.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("softQuota")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("softQuota")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GroupBlobStoreAPICreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GroupBlobStoreAPICreateRequest) UnmarshalBinary(b []byte) error {
	var res GroupBlobStoreAPICreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
