// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MaliciousRiskCountByEcosystem malicious risk count by ecosystem
//
// swagger:model MaliciousRiskCountByEcosystem
type MaliciousRiskCountByEcosystem struct {

	// count
	Count int64 `json:"count,omitempty"`

	// ecosystem
	Ecosystem string `json:"ecosystem,omitempty"`
}

// Validate validates this malicious risk count by ecosystem
func (m *MaliciousRiskCountByEcosystem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this malicious risk count by ecosystem based on context it is used
func (m *MaliciousRiskCountByEcosystem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MaliciousRiskCountByEcosystem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MaliciousRiskCountByEcosystem) UnmarshalBinary(b []byte) error {
	var res MaliciousRiskCountByEcosystem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
