// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NodeInformation node information
//
// swagger:model NodeInformation
type NodeInformation struct {

	// node Id
	NodeID string `json:"nodeId,omitempty"`
}

// Validate validates this node information
func (m *NodeInformation) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this node information based on context it is used
func (m *NodeInformation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NodeInformation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NodeInformation) UnmarshalBinary(b []byte) error {
	var res NodeInformation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
